name: App Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build Android app
        run: npx react-native bundle --platform android --dev false --bundle-output ./android/app/src/main/assets/index.android.bundle --entry-file ./index.js --out-file ./android/app/src/main/java/com/myproject/MainApplication.java
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: ./android/app/src/main/assets/index.android.bundle
