name: App Build
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # React Native generally works well with Java 11
          distribution: 'temurin'
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug
      - name: Upload Debug APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk